
version: '3'

services:
  mongodb:
    image: mongo:5
    ports:
        - 27018:27017
    volumes:
        - './data:/data/db'

  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'

  web:
    restart: on-failure
    build:
      context: ./
      dockerfile: ./web/Dockerfile.dev
    hostname: web
    ports:
      - '4500:5000'
    volumes:
      - ./web/node_modules:/app/node_modules
      - ./web/bin:/app/bin
      - ./web/collections:/app/collections
      - ./web/config:/app/config
      - ./web/migrations:/app/migrations
      - ./web/routes:/app/routes
      - ./web/server:/app/server
      - ./web/shared:/app/shared
      - ./web/app.js:/app/app.js
      - ./web/migrate-mongo-config.js:/app/migrate-mongo-config.js
      # - ./web:/app
      # - /app/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb

  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - web